//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YX.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Base_UserInfo
    {
        public Base_UserInfo()
        {
            this.Base_StaffOrganize = new HashSet<Base_StaffOrganize>();
            this.Base_UserRight = new HashSet<Base_UserRight>();
            this.Base_AppendPropertyInstance = new HashSet<Base_AppendPropertyInstance>();
            this.Base_UserRole = new HashSet<Base_UserRole>();
        }
    
        public string User_ID { get; set; }
        public string User_Code { get; set; }
        public string User_Account { get; set; }
        public string User_Pwd { get; set; }
        public string User_Name { get; set; }
        public string User_Sex { get; set; }
        public string Title { get; set; }
        public string Email { get; set; }
        public string Theme { get; set; }
        public Nullable<int> DeleteMark { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateUserId { get; set; }
        public string CreateUserName { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyUserId { get; set; }
        public string ModifyUserName { get; set; }
        public string User_Remark { get; set; }
    
        public virtual ICollection<Base_StaffOrganize> Base_StaffOrganize { get; set; }
        public virtual ICollection<Base_UserRight> Base_UserRight { get; set; }
        public virtual ICollection<Base_AppendPropertyInstance> Base_AppendPropertyInstance { get; set; }
        public virtual ICollection<Base_UserRole> Base_UserRole { get; set; }
    }
}
