//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YX.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Base_AppendPropertyInstance
    {
        public string PropertyInstance_ID { get; set; }
        public string Property_Control_ID { get; set; }
        public string PropertyInstance_Value { get; set; }
    
        public virtual Base_UserInfo Base_UserInfo { get; set; }
    }
}
