//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YX.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Sam_DBEntities : DbContext
    {
        public Sam_DBEntities()
            : base("name=Sam_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Base_SysMenu> Base_SysMenu { get; set; }
        public virtual DbSet<Base_UserRight> Base_UserRight { get; set; }
        public virtual DbSet<Base_Organization> Base_Organization { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Base_StaffOrganize> Base_StaffOrganize { get; set; }
        public virtual DbSet<Base_UserInfo> Base_UserInfo { get; set; }
        public virtual DbSet<Base_AppendPropertyInstance> Base_AppendPropertyInstance { get; set; }
        public virtual DbSet<Base_AppendProperty> Base_AppendProperty { get; set; }
        public virtual DbSet<Base_RoleRight> Base_RoleRight { get; set; }
        public virtual DbSet<Base_Roles> Base_Roles { get; set; }
        public virtual DbSet<Base_UserRole> Base_UserRole { get; set; }
        public virtual DbSet<Base_Log> Base_Log { get; set; }
    }
}
